repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.4
    hooks:
      - id: terraform_fmt
        args:
          - --arg=-recursive
          - --arg=-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yml
      - id: trailing-whitespace
