name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Self-hosted renovate
        uses: renovatebot/github-action@v40.1.7
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_BRANCH_PREFIX: "self-hosted-renovate/"
